# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Aptu Contributors

version = 1

[[annotations]]
path = ["**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Aptu Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["AptuKMP/**"]
precedence = "override"
SPDX-FileCopyrightText = "2026 Aptu Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["crates/**"]
precedence = "override"
SPDX-FileCopyrightText = "2026 Aptu Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [".github/**"]
precedence = "override"
SPDX-FileCopyrightText = "2026 Aptu Contributors"
SPDX-License-Identifier = "Apache-2.0"
